### ISSUE TITLE
Feature, History class, save and load function

### ISSUE THREAD

**Issue by Marcus9512** [DD2480-Group17/assignment2#17]
The history class should be able to save a compiled test to a file with a timestamp.

The history class should be able to load a requested test, via a commit id

**Comment by johannaii** [comment]
I have tried to build a unit test for the save() feature, but it is a little bit tricky because I already create the file in the method + the timestamp contains millisecond. You can test it and see that the file is created by running this lines:  
![Skärmavbild 2020-02-02 kl  11 30 35](https://user-images.githubusercontent.com/45517649/73606980-a56a7700-45b0-11ea-9a43-bb506c0c01a1.png)

Do you think it is enough? I could add a tutorial for how to test this feature in the README or in the class somewhere. If anyone else knows or have an idea how to create a unit test for my method hit me up!

**Comment by johannaii** [comment]
I have tried to build a unit test for the save() feature, but it is a little bit tricky because I already create the file in the method + the timestamp contains millisecond. You can test it and see that the file is created by running this lines:  

![Skärmavbild 2020-02-02 kl  11 54 32](https://user-images.githubusercontent.com/45517649/73607196-6be73b00-45b3-11ea-9d77-2456cdf386d4.png)

Do you think it is enough? I could add a tutorial for how to test this feature in the README or in the class somewhere. If anyone else knows or have an idea how to create a unit test for my method hit me up! Check the commit with ID fb370a5 (the other one is wrong and I deleted the old branch issue/17 with it).
